version: "3"

services:
  www:
    image: nginx:alpine
    container_name: portfolioapp
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
